# Generated by Django 6.0.2 on 2026-02-20 22:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("email_address", models.EmailField(max_length=254, unique=True)),
                ("full_name", models.CharField(blank=True, max_length=256, null=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_superuser", models.BooleanField(default=False)),
                (
                    "email_address_verified_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "phone_number_verified_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("blocked_at", models.DateTimeField(blank=True, null=True)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                ("last_login_ip", models.DateTimeField(blank=True, null=True)),
                ("password_expired_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "users",
            },
        ),
    ]
