# Generated by Django 6.0.2 on 2026-02-21 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monobit", "0001_create_user_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="Config",
            fields=[
                (
                    "key",
                    models.CharField(max_length=128, primary_key=True, serialize=False),
                ),
                ("value", models.JSONField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "config",
            },
        ),
    ]
