# Generated by Django 6.0.2 on 2026-02-22 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monobit", "0002_create_config_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("admin", "Admin"), ("owner", "Owner"), ("staff", "Staff")],
                default="staff",
                max_length=32,
            ),
        ),
    ]
