# Generated by Django 6.0.2 on 2026-02-23 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monobit", "0007_create_event_model"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="issuefingerprint",
            constraint=models.UniqueConstraint(
                fields=("issue", "project"), name="unique_issue_project_fingerprint"
            ),
        ),
    ]
