# Generated by Django 6.0.2 on 2026-02-28 18:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monobit", "0008_add_issue_fingerprint_constraint"),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("payload", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("retry_count", models.IntegerField(default=0)),
                ("available_at", models.DateTimeField(auto_now_add=True)),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                ("locked_by", models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                "db_table": "jobs",
                "indexes": [
                    models.Index(
                        condition=models.Q(("status", "pending")),
                        fields=["available_at"],
                        name="jobs_pending_available_idx",
                    )
                ],
            },
        ),
    ]
