# Generated by Django 6.0.2 on 2026-02-28 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("monobit", "0009_create_job_model"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="message",
        ),
        migrations.RemoveField(
            model_name="event",
            name="stacktrace",
        ),
    ]
