# Generated by Django 6.0.2 on 2026-02-28 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monobit", "0010_remove_message_and_stacktrace_fields_from_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="properties",
            field=models.JSONField(default=dict),
        ),
    ]
