# Generated by Django 6.0.2 on 2026-02-28 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monobit", "0011_add_properties_to_event_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="error",
            field=models.TextField(blank=True, null=True),
        ),
    ]
