# Generated by Django 6.0.2 on 2026-03-01 13:22

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monobit", "0012_add_error_to_job_field"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkerNode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("hostname", models.CharField(max_length=225, unique=True)),
                ("is_enabled", models.BooleanField(default=False)),
                ("desired_workers", models.IntegerField(default=1)),
                ("cpu_cores", models.PositiveIntegerField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "worker_nodes",
            },
        ),
        migrations.CreateModel(
            name="WorkerInstance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("worker_index", models.PositiveIntegerField()),
                ("worker_id", models.CharField(max_length=150, unique=True)),
                ("pid", models.IntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("starting", "Starting"),
                            ("running", "Running"),
                            ("stopping", "Stopping"),
                            ("stopped", "Stopped"),
                            ("crashed", "Crashed"),
                        ],
                        default="starting",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "last_heartbeat",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("restart_count", models.IntegerField(default=0)),
                ("is_enabled", models.BooleanField(default=False)),
                (
                    "worker_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instances",
                        to="monobit.workernode",
                    ),
                ),
            ],
            options={
                "db_table": "worker_instances",
                "indexes": [
                    models.Index(
                        fields=["status"], name="worker_inst_status_d9d243_idx"
                    ),
                    models.Index(
                        fields=["last_heartbeat"], name="worker_inst_last_he_7a0010_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("worker_node", "worker_index"),
                        name="unique_worker_index_per_node",
                    )
                ],
            },
        ),
    ]
