# Generated by Django 6.0.2 on 2026-03-01 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monobit", "0013_create_worker_and_worker_instance_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workerinstance",
            name="last_heartbeat",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="workerinstance",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
